# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: communication.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='communication.proto',
  package='foodbot_grpc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x63ommunication.proto\x12\x0c\x66oodbot_grpc\"\x19\n\tUserInput\x12\x0c\n\x04text\x18\x01 \x01(\t\"\"\n\x0bIngridients\x12\x13\n\x0bingridients\x18\x01 \x03(\t2\\\n\x12IngridientsService\x12\x46\n\x0eGetIngridients\x12\x17.foodbot_grpc.UserInput\x1a\x19.foodbot_grpc.Ingridients\"\x00\x62\x06proto3'
)




_USERINPUT = _descriptor.Descriptor(
  name='UserInput',
  full_name='foodbot_grpc.UserInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='foodbot_grpc.UserInput.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=62,
)


_INGRIDIENTS = _descriptor.Descriptor(
  name='Ingridients',
  full_name='foodbot_grpc.Ingridients',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ingridients', full_name='foodbot_grpc.Ingridients.ingridients', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['UserInput'] = _USERINPUT
DESCRIPTOR.message_types_by_name['Ingridients'] = _INGRIDIENTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserInput = _reflection.GeneratedProtocolMessageType('UserInput', (_message.Message,), {
  'DESCRIPTOR' : _USERINPUT,
  '__module__' : 'communication_pb2'
  # @@protoc_insertion_point(class_scope:foodbot_grpc.UserInput)
  })
_sym_db.RegisterMessage(UserInput)

Ingridients = _reflection.GeneratedProtocolMessageType('Ingridients', (_message.Message,), {
  'DESCRIPTOR' : _INGRIDIENTS,
  '__module__' : 'communication_pb2'
  # @@protoc_insertion_point(class_scope:foodbot_grpc.Ingridients)
  })
_sym_db.RegisterMessage(Ingridients)



_INGRIDIENTSSERVICE = _descriptor.ServiceDescriptor(
  name='IngridientsService',
  full_name='foodbot_grpc.IngridientsService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=100,
  serialized_end=192,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetIngridients',
    full_name='foodbot_grpc.IngridientsService.GetIngridients',
    index=0,
    containing_service=None,
    input_type=_USERINPUT,
    output_type=_INGRIDIENTS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_INGRIDIENTSSERVICE)

DESCRIPTOR.services_by_name['IngridientsService'] = _INGRIDIENTSSERVICE

# @@protoc_insertion_point(module_scope)
