# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import communication_pb2 as communication__pb2


class IngridientsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetIngridients = channel.unary_unary(
                '/foodbot_grpc.IngridientsService/GetIngridients',
                request_serializer=communication__pb2.UserInput.SerializeToString,
                response_deserializer=communication__pb2.Ingridients.FromString,
                )


class IngridientsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetIngridients(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IngridientsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetIngridients': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIngridients,
                    request_deserializer=communication__pb2.UserInput.FromString,
                    response_serializer=communication__pb2.Ingridients.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'foodbot_grpc.IngridientsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class IngridientsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetIngridients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/foodbot_grpc.IngridientsService/GetIngridients',
            communication__pb2.UserInput.SerializeToString,
            communication__pb2.Ingridients.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
